image:
  - macos-mojave
  - Ubuntu1804
  - Visual Studio 2017

version: 2.6.5.{build}

pull_requests:
  do_not_increment_build_number: true

configuration: Release

platform:
- x64

build:
  project: nx.sln
  verbosity: minimal

artifacts:
  - path: NXEngine-*.zip
    name: winbuild

  - path: NXEngine-*.dmg
    name: osxbuild

  - path: NXEngine-*.AppImage
    name: appimagebuild


deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: ''
    auth_token:
      secure: UNAaCG+KMRMqZqVEHpSgXTXZOJlqEQ/7nySQ6U/LutHjXnuqVNpYDxoqIW1hufI+
    draft: true
    force_update: true
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true


for:
-
  matrix:
    only:
      - image: Visual Studio 2017

  after_build:
   - ps: .\build-scripts\ci\win.package.ps1


-
  matrix:
    only:
      - image: Ubuntu1804

  install:
    - sudo apt update
    - sudo apt install -yqq libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libjpeg-dev libpng-dev ninja-build

  build_script:
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build/AppDir/usr -Bbuild -H.
    - ninja -Cbuild

  after_build:
    - build-scripts/ci/linux.deploy.sh

-
  matrix:
    only:
      - image: macos-mojave

  install:
    - brew update
    - brew install sdl2 sdl2_mixer sdl2_image libjpeg libpng ninja

  build_script:
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -Bbuild -H.
    - ninja -Cbuild

  after_build:
    - sh: export APPVEYOR_VNC_BLOCK=true
    - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
    - "if [ ${APPVEYOR_REPO_TAG} == \"true\" ];then sqlite3 \"$HOME/Library/Application Support/com.apple.TCC/TCC.db\" \"INSERT INTO access VALUES('kTCCServiceAppleEvents','$(dirname \"$0\")/appveyor-build-agent',1,1,1,X'fade0c000000002800000001000000080000001469862bbf79a6795b784518beed2ae09bf63e58ef',NULL,0,'com.apple.finder',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e66696e64657200000003',NULL,1605970638);\";fi"
    - build-scripts/ci/osx.deploy.sh
